name: Test ARC Action
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-repo
    container: debian:stable-slim
      # image: octopusdeploy/worker-tools:6.2-ubuntu.22.04
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"